const strings = {
    Home:'Home',
    Shorts:'Shorts',
    AddScreen:'AddScreen',
    Subscription:'Subscription',
    Profile:'Profile',
    OriginalAudio:'Songs Audio',
    Downloads:'Downloads',
    NoDownloadedVideo:'No downloaded videos yet.',
    History:'History',
    NoHistory:'No history yet.',
    ViewAll:'View all',
    ProfileName:'Amar Nath Ojha',
    ViewChannel:'View channel ',
    UserId:' @Amar_Ojha',
    NoResultFound:'No results found',
    RecentSearches:'Recent Searches',
    Settings:'Settings',
    Logout:'Logout',
    ShortsScreen:' Shorts',
    Forgot:'Forgot Password?',
    GoogleLogin:'Log in with Google',
    SignUp:'Sign up',
    All:'All',
    NoSubscribers:'No subscribed channels yet.',
    signInGoogle:'Log in with Google',
    // SignUp:'SignUp'
    }
    export default strings;