const ScreenNames = {
    SplashScreen: 'SplashScreen',
    SignInScreen: 'SignInScreen',
    SignUpScreen: 'SignUpScreen',
    BottomTab: 'BottomTab',
    Home: 'Home',
    Profile: 'Profile',
    Subscription: 'Subscription',
    Menu: 'Menu',
    Shorts:'Shorts',
    AddScreen:'AddScreen',
    VideoPlayer:'VideoPlayer',
    PlayerScreen:'PlayerScreen',
    HistoryScreen:'HistoryScreen',
    SettingScreen:'SettingScreen',
    SearchScreen:'SearchScreen',
    DownloadScreen:'DownloadScreen',
    SignInGoogle:'SignInGoogle',
};
export {ScreenNames};